language: php

php:
- 5.5
- 5.6

env:
- FLOW_VERSION=2.3.*
- FLOW_VERSION=2.2.*
- FLOW_VERSION=2.1.*

before_script:
- cd Build
- "./BeforeScriptTravis.sh"

script:
- php bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Ttree.Serializer/Tests/Unit
- php bin/phpcs --standard=TYPO3Flow Packages/Application/Ttree.Serializer
