language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - FLOW_VERSION=2.2.*
  # - FLOW_VERSION=dev-master

notifications:
  slack:
    rooms:
      - ttree:3qrP8hsRE2AAftIzFkjNVj94#general
      - ttree:3qrP8hsRE2AAftIzFkjNVj94#ci

before_script:
  - cd Build
  - ./BeforeScriptTravis.sh

script:
    - phpunit --coverage-clover=coverage.clover -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Ttree.Serializer/Tests/Unit